### ISSUE TITLE
CPT issues checklist

### ISSUE THREAD

**Issue by quantifish** [seacode/gmacs#170]
- [x] Fix up season length (season 2)
 - [x] Try fix initial conditions and recruitment devs at Jies values
 - [x] Check for local minima
 - [x] Try fix stage-2 selectivity at 1 if >1
 - [x] Check rec_ini and R0 are off in estimating initial numbers at length
 - [x] Check that the likelihoods for indices and LFs are the same
 - [x] Check the likelihood components from 2015 model, should be same with Gmacs runs

**Comment by quantifish** [comment]
Jies objective functions look rather different to ours

    FUNCTION calculate_obj_function
     int j, i, ii;
     LogLike.initialize();

     // Loglikelihoods (less additive constants)

     // 1a. Retained catch number of "legals"
 // LogLike(1) = -0.5*norm2(log(x_ret + 0.001) - log(X_ret + 0.001));

 // 1b. Retained catch biomass
  LogLike(1) = -0.5*norm2(log(x_ret_b + 0.001) - log(X_ret_b + 0.001));

 // 2a. Trawl suvey abundance lognormally distributed about predicted value
 //LogLike(2) = -0.5*norm2(elem_div(log(x_ts)-log(X_ts),sig_ts));

 // 2b. Trawl survey biomass lognormally distributed about predicted value
 LogLike(2) = -0.5*norm2(elem_div(log(b_ts)-log(B_ts),sig_ts_b));

 // 3. Pot survey abundance lognormally distributed about predicted value
 LogLike(3) = -0.5*norm2(elem_div(log(x_ps)-log(X_ps),sig_ps));

 // 4. Trawl survey proportions are multinomial wrt predicted proportions
   // LogLike(4) = effn_ts*rowsum(elem_prod(p_ts,log(P_ts+0.01)));
 for (j=1;j<=nyrs_ts;j++)
 {
   for(i=1;i<=3;i++)
   {
     t1  = p_ts(j,i)*(1.0-p_ts(j,i))+0.1/3.0;
     t0 = log(mfexp(-1.*square(p_ts(j,i)-P_ts(j,i))*effn_ts(j)/(2.0*t1))+0.01);
 //    Like_ts(j,i) = (p_ts(j,i)-P_ts(j,i))*sqrt(effn_ts(j)/(2.0*t1));
     LogLike(4) += (-0.5)*log(6.29*t1)-log(sqrt(1.0/effn_ts(j)))+t0;
   }
 }

 // 5. Pot survey proportions are multinomial wrt predicted proportions
   //  LogLike(5) = effn_ps*rowsum(elem_prod(p_ps,log(P_ps+0.01)));
 for (j=1;j<=nyrs_ps;j++)
 {
   for(i=1;i<=3;i++)
   {
     t1  = p_ps(j,i)*(1.0-p_ps(j,i))+0.1/3.0;
     t0 = log(mfexp(-1.*square(p_ps(j,i)-P_ps(j,i))*effn_ps(j)/(2.0*t1))+0.01);
 //    Like_ps(j,i) = (p_ps(j,i)-P_ps(j,i))*sqrt(effn_ps(j)/(2.0*t1));
     LogLike(5) += (-0.5)*log(6.29*t1)-log(sqrt(1.0/effn_ps(j)))+t0;
   }
 }

 // 6. Observer proportions are multinomial wrt predicted proportions
   //LogLike(6) = effn_ob*rowsum(elem_prod(p_ob,log(P_ob+0.01)));
 for (j=1;j<=nyrs_ob;j++)
 {
   for(i=1;i<=3;i++)
   {
     t1  = p_ob(j,i)*(1.0-p_ob(j,i))+0.1/3.0;
     t0 = log(mfexp(-1.*square(p_ob(j,i)-P_ob(j,i))*effn_ob(j)/(2.0*t1))+0.01);
 //    Like_ob(j,i) = (p_ob(j,i)-P_ob(j,i))*sqrt(effn_ob(j)/(2.0*t1));
     LogLike(6) += (-0.5)*log(6.29*t1)-log(sqrt(1.0/effn_ob(j)))+t0;
   }
 }
 //7. Pot discard male biomass
  LogLike(7) = -0.5*norm2(log(x_ob1 + 0.001) - log(X_ob1 + 0.001));
  LogLike(8) = -0.5*norm2(log(x_ob2 + 0.001) - log(X_ob2 + 0.001));

     // 9. + 10. Groundfish trawl and fixed-gear mortality biomass
     LogLike(9) = 0.0; LogLike(10) = 0.0;
     for(j=1;j<=nyrs_gf;j++)
     {
       LogLike(9) += -0.5*square(log(gft_mort(j)+0.01) - log(B_gft(yid_gf(j))+0.01));
       LogLike(10) += -0.5*square(log(gff_mort(j)+0.01) - log(B_gff(yid_gf(j))+0.01));
     }

     // Quadratic (normal) penalties

     // 1. Model recruit deviations
     Pen(1) = 0.5*norm2(log_New_dev);

     // 2. Directed fishery log fishing mortality deviations
     Pen(2) = 0.5*norm2(log_Fpf_dev);

     // 3. + 4. Gft and Gff log fishing mortality deviations
     Pen(3) = 0.5*norm2(log_Fgft_dev);
     Pen(4) = 0.5*norm2(log_Fgff_dev);


     // Objective function
     f = Pw*Pen - Lw*LogLike;
